// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartButton_linx from "./islands/AddToCartButton/linx.tsx";
import * as $AddToCartButton_nuvemshop from "./islands/AddToCartButton/nuvemshop.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $Faq from "./islands/Faq.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart_linx from "./islands/Header/Cart/linx.tsx";
import * as $Header_Cart_nuvemshop from "./islands/Header/Cart/nuvemshop.tsx";
import * as $Header_Cart_shopify from "./islands/Header/Cart/shopify.tsx";
import * as $Header_Cart_vnda from "./islands/Header/Cart/vnda.tsx";
import * as $Header_Cart_vtex from "./islands/Header/Cart/vtex.tsx";
import * as $Header_Cart_wake from "./islands/Header/Cart/wake.tsx";
import * as $Header_Drawers from "./islands/Header/Drawers.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $Map_Map from "./islands/Map/Map.tsx";
import * as $Map_MapMobile from "./islands/Map/MapMobile.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $ProductAccordionInfo from "./islands/ProductAccordionInfo.tsx";
import * as $ProductCardSliderImages from "./islands/ProductCardSliderImages.tsx";
import * as $ProductCardWithBannerMobile from "./islands/ProductCardWithBannerMobile.tsx";
import * as $ProductGalleryMobile from "./islands/ProductGalleryMobile.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $ProductImages from "./islands/ProductImages.tsx";
import * as $ProductSizeVariantSelector from "./islands/ProductSizeVariantSelector.tsx";
import * as $ProductSizebayButtons from "./islands/ProductSizebayButtons.tsx";
import * as $ProductVariantSelector from "./islands/ProductVariantSelector.tsx";
import * as $ProxyIframe from "./islands/ProxyIframe.tsx";
import * as $SIzebayIframe from "./islands/SIzebayIframe.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $Share_ShareProduct from "./islands/Share/ShareProduct.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $ShowMore from "./islands/ShowMore.tsx";
import * as $WishlistButton_vtex from "./islands/WishlistButton/vtex.tsx";
import * as $WishlistButton_wake from "./islands/WishlistButton/wake.tsx";
import * as $WishlistMessageLogin from "./islands/WishlistMessageLogin.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartButton/linx.tsx": $AddToCartButton_linx,
    "./islands/AddToCartButton/nuvemshop.tsx": $AddToCartButton_nuvemshop,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/Faq.tsx": $Faq,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart/linx.tsx": $Header_Cart_linx,
    "./islands/Header/Cart/nuvemshop.tsx": $Header_Cart_nuvemshop,
    "./islands/Header/Cart/shopify.tsx": $Header_Cart_shopify,
    "./islands/Header/Cart/vnda.tsx": $Header_Cart_vnda,
    "./islands/Header/Cart/vtex.tsx": $Header_Cart_vtex,
    "./islands/Header/Cart/wake.tsx": $Header_Cart_wake,
    "./islands/Header/Drawers.tsx": $Header_Drawers,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/Map/Map.tsx": $Map_Map,
    "./islands/Map/MapMobile.tsx": $Map_MapMobile,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/ProductAccordionInfo.tsx": $ProductAccordionInfo,
    "./islands/ProductCardSliderImages.tsx": $ProductCardSliderImages,
    "./islands/ProductCardWithBannerMobile.tsx": $ProductCardWithBannerMobile,
    "./islands/ProductGalleryMobile.tsx": $ProductGalleryMobile,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/ProductImages.tsx": $ProductImages,
    "./islands/ProductSizeVariantSelector.tsx": $ProductSizeVariantSelector,
    "./islands/ProductSizebayButtons.tsx": $ProductSizebayButtons,
    "./islands/ProductVariantSelector.tsx": $ProductVariantSelector,
    "./islands/ProxyIframe.tsx": $ProxyIframe,
    "./islands/SIzebayIframe.tsx": $SIzebayIframe,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/Share/ShareProduct.tsx": $Share_ShareProduct,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/ShowMore.tsx": $ShowMore,
    "./islands/WishlistButton/vtex.tsx": $WishlistButton_vtex,
    "./islands/WishlistButton/wake.tsx": $WishlistButton_wake,
    "./islands/WishlistMessageLogin.tsx": $WishlistMessageLogin,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
